version: "3.0"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mahalaxmi_sandwich
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
  springboot:
    build: .
    container_name: pos_cafe_spring_server
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: mahalaxmi_sandwich
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: